name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
publish_to: none
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 2.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  easy_localization:
    git:
      url: https://github.com/summit-fi/easy_localization.git
      ref: develop

  connectivity_plus: ^6.0.3
  csv: ^5.0.1
  flutter: { sdk: flutter }
  http: ^1.1.0
  path_provider: ^2.1.1
  xml: ^6.1.0
  yaml: ^3.1.1
  universal_io: ^2.2.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.6
